Update .c and .h files and add bin/format and bin/lint

diff --git a/bin/format b/bin/format
--- a/bin/format
+++ b/bin/format
@@ -1,9 +1,7 @@
 #!/bin/bash
 
-# Format all C/C++ files in the repository
-find . \( -name '*.c' -o -name '*.h' -o -name '*.cpp' -o -name '*.hpp' \) \
-  -not -path "./build/*" \
-  -not -path "./vendor/*" \
-  -exec clang-format -i {} +
+set -e  # Exit on error
+
+clang-format -i src/*.c src/**/*.c src/*.h src/**/*.h ext/**/*.c ext/**/*.h
 
 echo "Formatting complete!"
